# Generated by Django 6.0.3 on 2026-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('last_fetch_date', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
