# Generated by Django 6.0.3 on 2026-04-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateActionSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetch_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('corporate_action_type', models.CharField(choices=[('bonus', 'Bonus Share'), ('right', 'Right Share'), ('cash_dividend', 'Cash Dividend')], max_length=20)),
                ('book_close_date', models.DateField()),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('bonus_pct', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('cash_dividend_pct', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('right_share_pct', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'corporate_actions',
                'indexes': [models.Index(fields=['symbol'], name='idx_ca_symbol'), models.Index(fields=['book_close_date'], name='idx_ca_book_close'), models.Index(fields=['listing_date'], name='idx_ca_listing')],
                'constraints': [models.UniqueConstraint(fields=('book_close_date', 'corporate_action_type', 'symbol'), name='unique_corporate_action')],
            },
        ),
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn_no', models.CharField(max_length=255, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('trn_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('broker_commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('nepse_commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('sebo_commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dp_charge', models.DecimalField(decimal_places=4, max_digits=20)),
                ('regulatory_fee', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_transactions',
                'indexes': [models.Index(fields=['client_name', 'symbol', 'date'], name='idx_client_symbol_date')],
            },
        ),
    ]
