# Generated by Django 6.0.3 on 2026-03-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_snapshot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('share_type', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.CharField(db_index=True, max_length=50)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=20)),
                ('nepse_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sebo_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('broker_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dp_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
