# Generated by Django 6.0.3 on 2026-03-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_snapshot', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='share_type',
        ),
    ]
