# Generated by Django 6.0.3 on 2026-04-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_snapshot', '0003_remove_transaction_share_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn_no', models.CharField(max_length=255, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('trn_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('broker_commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('nepse_commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('sebo_commission', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dp_charge', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_transactions',
            },
        ),
        migrations.DeleteModel(
            name='CorporateAction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddIndex(
            model_name='dailytransaction',
            index=models.Index(fields=['client_name', 'symbol', 'date'], name='idx_client_symbol_date'),
        ),
    ]
