# Generated by Django 6.0.3 on 2026-04-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_snapshot', '0004_dailytransaction_delete_corporateaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('corporate_action_type', models.CharField(choices=[('bonus', 'Bonus Share'), ('right', 'Right Share'), ('cash_dividend', 'Cash Dividend')], max_length=20)),
                ('book_close_date', models.DateField()),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('bonus_pct', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('cash_dividend_pct', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('right_share_pct', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'corporate_actions',
                'indexes': [models.Index(fields=['symbol'], name='idx_ca_symbol'), models.Index(fields=['book_close_date'], name='idx_ca_book_close'), models.Index(fields=['listing_date'], name='idx_ca_listing')],
                'constraints': [models.UniqueConstraint(fields=('book_close_date', 'corporate_action_type', 'symbol'), name='unique_corporate_action')],
            },
        ),
    ]
