# Generated by Django 6.0.3 on 2026-04-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_snapshot', '0005_corporateaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateActionSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetch_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
